# Generated by Django 5.2.5 on 2025-08-13 01:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0002_remove_attempt_quiz_remove_attempt_user_and_more'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título do Quiz')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('total_questions', models.PositiveIntegerField(default=20, verbose_name='Número Total de Perguntas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='learning.topic', verbose_name='Tópico')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Texto da Pergunta')),
                ('choices', models.JSONField(verbose_name='Opções de Resposta')),
                ('correct_answer', models.CharField(max_length=10, verbose_name='Resposta Correta')),
                ('difficulty', models.CharField(choices=[('EASY', 'Fácil'), ('MODERATE', 'Moderada'), ('HARD', 'Difícil')], default='MODERATE', max_length=10, verbose_name='Nível de Dificuldade')),
                ('explanation', models.TextField(blank=True, verbose_name='Justificativa da Resposta')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='learning.subtopic', verbose_name='Subtópico Específico')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Pontuação (%)')),
                ('correct_answers_count', models.PositiveIntegerField(default=0, verbose_name='Respostas Corretas')),
                ('incorrect_answers_count', models.PositiveIntegerField(default=0, verbose_name='Respostas Incorretas')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Conclusão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessment.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Tentativa',
                'verbose_name_plural': 'Tentativas',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=10, verbose_name='Resposta do Usuário')),
                ('is_correct', models.BooleanField(verbose_name='Está Correta?')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessment.attempt', verbose_name='Tentativa')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessment.question', verbose_name='Pergunta')),
            ],
            options={
                'verbose_name': 'Resposta do Usuário',
                'verbose_name_plural': 'Respostas dos Usuários',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
