# Generated by Django 5.1.7 on 2025-08-12 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título da Disciplina')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['title'],
                'unique_together': {('user', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Tópico')),
                ('slug', models.SlugField(blank=True, help_text='Identificador único para a URL, gerado a partir do título.', max_length=220, unique=True)),
                ('suggested_study_plan', models.TextField(blank=True, null=True, verbose_name='Plano de Estudo Sugerido')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='learning.course', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Tópico',
                'verbose_name_plural': 'Tópicos',
                'ordering': ['order', 'title'],
                'unique_together': {('course', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Subtópico')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Detalhes')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Concluído')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='learning.topic', verbose_name='Tópico')),
            ],
            options={
                'verbose_name': 'Subtópico',
                'verbose_name_plural': 'Subtópicos',
                'ordering': ['order', 'title'],
            },
        ),
    ]
