"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import sys
from decouple import config
from pathlib import Path
from apps.accounts.apps import AccountsConfig
from apps.core.apps import CoreConfig
from apps.learning.apps import LearningConfig
from apps.scheduling.apps import SchedulingConfig
from apps.assessment.apps import AssessmentConfig
from apps.studychat.apps import StudychatConfig
from apps.analytics.apps import AnalyticsConfig
# --- INÍCIO DA CORREÇÃO DEFINITIVA PARA IMPORTAÇÃO DOS APPS ---

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Crie o caminho para a pasta 'apps'
APPS_DIR = BASE_DIR / 'apps'

# Adicione a pasta 'apps' ao caminho de busca do Python
sys.path.insert(0, str(APPS_DIR))

# --- FIM DA CORREÇÃO DEFINITIVA ---

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['testserver', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    # MEUS APPS (PRIMEIRO)
    # O app que define o AUTH_USER_MODEL deve vir antes de 'django.contrib.auth'
    'apps.accounts.apps.AccountsConfig',
    'apps.core.apps.CoreConfig',
    'apps.learning.apps.LearningConfig',
    'apps.scheduling.apps.SchedulingConfig',
    'apps.assessment.apps.AssessmentConfig',
    'apps.studychat.apps.StudychatConfig',
    'apps.analytics.apps.AnalyticsConfig',
    'rest_framework',# Django Rest Framework
    'rest_framework.authtoken',# Djoser precisa deste
    'rest_framework_simplejwt.token_blacklist',
    'djoser',

    # APPS PADRÃO DO DJANGO (DEPOIS)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_spectacular',  # Para documentação OpenAPI
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Configuração do Django Rest Framework (DRF)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # Define JWT como o método principal de autenticação para a API
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        # Exige que os usuários estejam autenticados por padrão
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Configuração do Simple JWT
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60), # Duração do token de acesso (curto)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),    # Duração do token de refresh (longo)
    'ROTATE_REFRESH_TOKENS': True, # Opcional: gera um novo refresh token a cada uso
    'BLACKLIST_AFTER_ROTATION': True, # Opcional: invalida o refresh token antigo
}

# Configuração do frontend para links enviados por e-mail
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')


# Configuração do Djoser
DJOSER = {
    'PASSWORD_RESET_CONFIRM_URL': '#/password/reset/confirm/{uid}/{token}',
    'USERNAME_RESET_CONFIRM_URL': '#/username/reset/confirm/{uid}/{token}',
    'ACTIVATION_URL': 'auth/activate/{uid}/{token}',
    'SEND_ACTIVATION_EMAIL': True,
    'SERIALIZERS': {
        'user_create': 'apps.accounts.serializers.UserCreateSerializer',
        'user': 'apps.accounts.serializers.UserSerializer',
        'current_user': 'apps.accounts.serializers.UserSerializer',
        'set_password': 'apps.accounts.serializers.SetPasswordSerializer',
    },
    'EMAIL': {
        'activation': 'apps.accounts.email.ActivationEmail',
        'confirmation': 'apps.accounts.email.ConfirmationEmail',
        'password_reset': 'apps.accounts.email.PasswordResetEmail',
        'password_reset_confirmation': 'apps.accounts.email.PasswordResetConfirmationEmail',
        'password_changed_confirmation': 'apps.accounts.email.PasswordChangedConfirmationEmail',
        'username_changed_confirmation': 'apps.accounts.email.UsernameChangedConfirmationEmail',
        'username_reset': 'apps.accounts.email.UsernameResetEmail',
        'username_reset_confirmation': 'apps.accounts.email.UsernameResetConfirmationEmail',
    },
    'USER_ID_FIELD': 'id',
    'LOGIN_FIELD': 'email', # Usar email para login
    'PERMISSIONS': {
        'set_password': (
            'rest_framework.permissions.IsAuthenticated',
        ),
        'password_reset': (
            'rest_framework.permissions.AllowAny',
        ),
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SECRET_KEY = config('SECRET_KEY')
DEEPSEEK_API_KEY = config('DEEPSEEK_API_KEY')

EMAIL_BACKEND = config(
    'EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend'
)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='no-reply@example.com')

AUTH_USER_MODEL = 'accounts.User'


if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:'  # Banco em memória para testes mais rápidos
        }
    }
    
    # Desabilitar migrações desnecessárias em testes
    class DisableMigrations:
        def __contains__(self, item):
            return True
        def __getitem__(self, item):
            return None
    
    MIGRATION_MODULES = DisableMigrations()
    
    
SPECTACULAR_SETTINGS = {
    'TITLE': 'StudyPlatform API',
    'DESCRIPTION': 'Documentação da API para a plataforma de estudos StudyPlatform',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,  # Exclui o endpoint /schema/ da interface Swagger
    'TAGS': [
        {
            'name': 'Autenticação JWT',
            'description': 'Fluxos de renovação e verificação de tokens JWT fornecidos pelo Djoser/Simple JWT.',
        },
    ],
    'POSTPROCESSING_HOOKS': [
        'config.openapi_hooks.add_jwt_highlight_to_schema',
    ],
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'docExpansion': 'list',
        'defaultModelsExpandDepth': -1,
        'persistAuthorization': True,
        'displayRequestDuration': True,
        'filter': True,
        'tagsSorter': 'alpha',
        'operationsSorter': 'alpha',
    },
    'REDOC_SETTINGS': {
        'hideDownloadButton': True,
        'expandResponses': '200,201',
        'tagGroups': [
            {
                'name': 'Fluxos de Autenticação',
                'tags': ['Autenticação JWT'],
            },
        ],
    },
    # Adicione mais configurações aqui conforme necessário
    # https://drf-spectacular.readthedocs.io/en/latest/settings.html
}
