# Generated by Django 5.1.7 on 2025-08-12 22:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data do Estudo')),
                ('minutes_studied', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minutos Estudados')),
                ('notes', models.TextField(blank=True, help_text='O que você aprendeu? Quais foram suas dificuldades?', null=True, verbose_name='Anotações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_logs', to='learning.course', verbose_name='Disciplina')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_logs', to='learning.topic', verbose_name='Tópico Estudado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Registro de Estudo',
                'verbose_name_plural': 'Registros de Estudo',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da Semana')),
                ('minutes_planned', models.PositiveIntegerField(help_text='Quantos minutos você planeja estudar esta disciplina neste dia.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minutos Planejados')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='learning.course', verbose_name='Disciplina')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Plano de Estudo Semanal',
                'verbose_name_plural': 'Planos de Estudo Semanais',
                'ordering': ['user', 'day_of_week', 'course'],
                'unique_together': {('user', 'course', 'day_of_week')},
            },
        ),
    ]
